balanceSheet=Balance Sheet
glcode=GL CODE
name=Name
description=Description
balance=Balance
assets=Assets
totalAssets=Total Assets
liability=Liabilities
totalLiabilities=Total Liabilities
totalLiabilitiesAndEquity=Total Liabilities and Equity
equity=Equity
totalEquities=Total Equities
branchName=Branch :
asOn=As at:
retainedEarnings=Retained Earnings
currentMonth=Current Month
previousMonth=Previous Month
previousYear=Previous Year
monthOnMonth=Month On Month
yearToDate=Year to Date
