dependencies {
    implementation project(':fineract-core')
    implementation project(':fineract-provider')
    implementation project(':fineract-savings')
    implementation project(':fineract-charge')
    implementation project(':fineract-accounting')
    implementation project(':fineract-tax')
}
